# Generated by Django 3.0.5 on 2020-10-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=70)),
                ('likedlist', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
